
********************************************************************************
* 
* Attention: 
* You may have tried to build FHI-aims without specifying a make target.
* To build FHI-aims, you must specify a target, e.g.:
* 
* '> make scalapack.mpi',
* ..., but NOT simply
* '> make' .
*  
* Before you type any form of make, you must specify a minimum set of
* variables that define how you will be compiling: Which compiler, which
* compiler optimization, which linear algebra libraries. All of these
* are performance critical and we cannot make this decision automatically
* on a specific computer.
*
* See the documentation (manual) for a more complete explanation, including
* how to set up your own file 'make.sys' with the necessary information on
* compilers etc.
* 
*********************************************************************************

