set(CMAKE_Fortran_COMPILER "/usr/bin/mpif90" CACHE STRING "")
set(CMAKE_Fortran_FLAGS "-O3 -p" CACHE STRING "")
set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE STRING "")
set(CMAKE_C_FLAGS "-O3 -p" CACHE STRING "")
set(LIB_PATHS "/opt/intel/mkl/lib/intel64" CACHE STRING "")
set(LIBS "mkl_intel_lp64 mkl_sequential mkl_core mkl_blacs_intelmpi_lp64 mkl_scalapack_lp64" CACHE STRING "")
set(USE_MPI ON CACHE BOOL "")
set(USE_SCALAPACK ON CACHE BOOL "")
set(USE_C_FILES ON CACHE BOOL "")
set(USE_SPGLIB ON CACHE BOOL "")
set(USE_LIBXC ON CACHE BOOL "")
set(USE_HDF5 OFF CACHE BOOL "")
